# Generated by Django 5.0.6 on 2025-05-24 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_name', models.CharField(max_length=50, verbose_name='Derslik Adı')),
                ('classroom_code', models.CharField(max_length=50, unique=True, verbose_name='Derslik Kodu')),
                ('classroom_capacity', models.PositiveIntegerField(verbose_name='Derslik Kapasitesi')),
            ],
            options={
                'verbose_name': 'derslik',
                'verbose_name_plural': 'derslikler',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='Ders Kodu')),
                ('course_credit', models.PositiveIntegerField(verbose_name='Ders Kredisi')),
                ('course_level', models.PositiveIntegerField(verbose_name='Ders Seviyesi')),
            ],
            options={
                'verbose_name': 'ders',
                'verbose_name_plural': 'dersler',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Pzt', 'Pazartesi'), ('Sal', 'Salı'), ('Çrş', 'Çarşamba'), ('Prş', 'Perşembe'), ('Cum', 'Cuma'), ('Cmt', 'Cumartesi'), ('Pzr', 'Pazar')], max_length=3, verbose_name='Günler')),
                ('start_time', models.TimeField(verbose_name='Başlama Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.classroom', verbose_name='Derslik')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course', verbose_name='Ders')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role__title': 'Öğretim Elemanı'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Öğretim Elemanı')),
            ],
            options={
                'verbose_name': 'ders programı',
                'verbose_name_plural': 'ders programları',
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_day', models.DateField(verbose_name='Sınav Günü')),
                ('start_time', models.TimeField(verbose_name='Başlama Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'sınav programı',
                'verbose_name_plural': 'sınav programları',
            },
        ),
        migrations.CreateModel(
            name='ExamSeatingArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, verbose_name='Öğrenci No')),
                ('seat_number', models.PositiveIntegerField(verbose_name='Sıra No')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.classroom', verbose_name='Derslik')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.examschedule', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'sınav oturma düzeni',
                'verbose_name_plural': 'sınav oturma düzenleri',
            },
        ),
        migrations.CreateModel(
            name='InstructorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Pzt', 'Pazartesi'), ('Sal', 'Salı'), ('Çrş', 'Çarşamba'), ('Prş', 'Perşembe'), ('Cum', 'Cuma'), ('Cmt', 'Cumartesi'), ('Pzr', 'Pazar')], max_length=3, verbose_name='Gün')),
                ('start_time', models.TimeField(verbose_name='Başlama Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.classroom', verbose_name='Derslik')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course', verbose_name='Ders')),
                ('instructor', models.ForeignKey(limit_choices_to={'role__title': 'Öğretim Elemanı'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğretim Elemanı')),
            ],
            options={
                'verbose_name': 'öğretim elemanı programı',
                'verbose_name_plural': 'öğretim elemanı programları',
            },
        ),
        migrations.CreateModel(
            name='InvigilatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.examschedule', verbose_name='Sınav')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Görevli')),
            ],
            options={
                'verbose_name': 'görevli ataması',
                'verbose_name_plural': 'görevli atamaları',
            },
        ),
    ]
